// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpVQ8oLLK9dCW4jhXaWLgTFyIRxTAxjK4',
    appId: '1:351725511967:web:f2e83f053a67b08a8c3c2a',
    messagingSenderId: '351725511967',
    projectId: 'tomato-534f4',
    authDomain: 'tomato-534f4.firebaseapp.com',
    storageBucket: 'tomato-534f4.firebasestorage.app',
    measurementId: 'G-8G83C4CEL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYYrKc_jCY24HU8NBqHZynKAa8zDowOAM',
    appId: '1:351725511967:android:c0b610b240b236538c3c2a',
    messagingSenderId: '351725511967',
    projectId: 'tomato-534f4',
    storageBucket: 'tomato-534f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz9bQpYYYTaSDJ5B6Eex4WQnhn6__-tIw',
    appId: '1:351725511967:ios:7ffee526c848b4808c3c2a',
    messagingSenderId: '351725511967',
    projectId: 'tomato-534f4',
    storageBucket: 'tomato-534f4.firebasestorage.app',
    iosBundleId: 'com.example.tomato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz9bQpYYYTaSDJ5B6Eex4WQnhn6__-tIw',
    appId: '1:351725511967:ios:7ffee526c848b4808c3c2a',
    messagingSenderId: '351725511967',
    projectId: 'tomato-534f4',
    storageBucket: 'tomato-534f4.firebasestorage.app',
    iosBundleId: 'com.example.tomato',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpVQ8oLLK9dCW4jhXaWLgTFyIRxTAxjK4',
    appId: '1:351725511967:web:1237daacfcdda8648c3c2a',
    messagingSenderId: '351725511967',
    projectId: 'tomato-534f4',
    authDomain: 'tomato-534f4.firebaseapp.com',
    storageBucket: 'tomato-534f4.firebasestorage.app',
    measurementId: 'G-DQXVLJ75BX',
  );
}
